FROM golang:1.24.13 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build \
    -ldflags="-s -w -X 'miniflux.app/v2/internal/version.Version=2.2.12'" \
    -o /app/miniflux .

FROM scratch

COPY --from=builder /app/miniflux /usr/local/bin/miniflux
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

CMD ["miniflux"]